--- #YAML:1.0
name:               Apache-Bootstrap
version:            0.07
abstract:           Bootstraps dual life mod_perl and mod_perl2 Apache modules
author:
    - Fred Moyer <fred@redhotpenguin.com>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:  {}
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.52
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
